In [1]:
import pandas as pd
import numpy as np

In [2]:
demographic_df = pd.read_csv("CHSICorrelations/data/CHSI_dataset/DEMOGRAPHICS.csv")

In [3]:
demographic_df.head()

,State_FIPS_Code,County_FIPS_Code,CHSI_County_Name,CHSI_State_Name,CHSI_State_Abbr,Strata_ID_Number,Strata_Determining_Factors,Number_Counties,Population_Size,Min_Population_Size,...,Max_Black,Native_American,Min_Native_American,Max_Native_American,Asian,Min_Asian,Max_Asian,Hispanic,Min_Hispanic,Max_Hispanic
0,1,1,Autauga,Alabama,AL,29,"frontier status, population size, poverty, age",37,48612,28447,...,17.3,0.5,0.1,1.1,0.6,0.2,2.2,1.7,0.8,19.2
1,1,3,Baldwin,Alabama,AL,16,"frontier status, population size, poverty, age",27,162586,118395,...,14.1,0.5,0.1,1.1,0.4,0.4,3.3,2.3,0.8,13.7
2,1,5,Barbour,Alabama,AL,51,"frontier status, population size, poverty, age...",33,28414,27269,...,50.7,0.4,0.2,7.1,0.3,0.2,2.3,3.1,1.0,67.7
3,1,7,Bibb,Alabama,AL,42,"frontier status, population size, poverty, age",53,21516,8134,...,35.4,0.3,0.1,2.6,0.1,0.1,1.5,1.4,1.2,46.9
4,1,9,Blount,Alabama,AL,28,"frontier status, population size, poverty, age",39,55725,29009,...,20.5,0.5,0.1,0.9,0.2,0.3,2.2,6.3,0.8,6.3

In [4]:
riskfactor_df = pd.read_csv("CHSICorrelations/data/CHSI_dataset/RISKFACTORSANDACCESSTOCARE.csv")

In [5]:
riskfactor_df.head()

,State_FIPS_Code,County_FIPS_Code,CHSI_County_Name,CHSI_State_Name,CHSI_State_Abbr,Strata_ID_Number,No_Exercise,CI_Min_No_Exercise,CI_Max_No_Exercise,Few_Fruit_Veg,...,Diabetes,CI_Min_Diabetes,CI_Max_Diabetes,Uninsured,Elderly_Medicare,Disabled_Medicare,Prim_Care_Phys_Rate,Dentist_Rate,Community_Health_Center_Ind,HPSA_Ind
0,1,1,Autauga,Alabama,AL,29,27.8,20.7,34.9,78.6,...,14.2,9.1,19.3,5690,4762,1209,45.3,22.6,1,2
1,1,3,Baldwin,Alabama,AL,16,27.2,23.2,31.2,76.2,...,7.2,5.2,9.3,19798,22635,3839,67.0,30.8,1,2
2,1,5,Barbour,Alabama,AL,51,-1111.1,-1111.1,-1111.1,-1111.1,...,6.6,2.0,11.3,5126,3288,1092,45.8,24.6,1,2
3,1,7,Bibb,Alabama,AL,42,-1111.1,-1111.1,-1111.1,86.6,...,13.1,4.7,21.5,3315,2390,974,41.8,18.6,1,1
4,1,9,Blount,Alabama,AL,28,33.5,26.3,40.6,74.6,...,8.4,4.4,12.4,8131,5019,1300,16.2,10.8,2,1

In [6]:
demo_riskfact_df = pd.merge(demographic_df, riskfactor_df, how ="inner", on = ["State_FIPS_Code", "County_FIPS_Code"])

In [7]:
demo_riskfact_df.head()

,State_FIPS_Code,County_FIPS_Code,CHSI_County_Name_x,CHSI_State_Name_x,CHSI_State_Abbr_x,Strata_ID_Number_x,Strata_Determining_Factors,Number_Counties,Population_Size,Min_Population_Size,...,Diabetes,CI_Min_Diabetes,CI_Max_Diabetes,Uninsured,Elderly_Medicare,Disabled_Medicare,Prim_Care_Phys_Rate,Dentist_Rate,Community_Health_Center_Ind,HPSA_Ind
0,1,1,Autauga,Alabama,AL,29,"frontier status, population size, poverty, age",37,48612,28447,...,14.2,9.1,19.3,5690,4762,1209,45.3,22.6,1,2
1,1,3,Baldwin,Alabama,AL,16,"frontier status, population size, poverty, age",27,162586,118395,...,7.2,5.2,9.3,19798,22635,3839,67.0,30.8,1,2
2,1,5,Barbour,Alabama,AL,51,"frontier status, population size, poverty, age...",33,28414,27269,...,6.6,2.0,11.3,5126,3288,1092,45.8,24.6,1,2
3,1,7,Bibb,Alabama,AL,42,"frontier status, population size, poverty, age",53,21516,8134,...,13.1,4.7,21.5,3315,2390,974,41.8,18.6,1,1
4,1,9,Blount,Alabama,AL,28,"frontier status, population size, poverty, age",39,55725,29009,...,8.4,4.4,12.4,8131,5019,1300,16.2,10.8,2,1

In [ ]:
riskfactor_df = riskfactor_df.melt(id_vars=["CHSI_State_Name", "CHSI_State_Abbr", "CHSI_County_Name", "Number_Counties",
                                           ], 
        var_name="Date", 
        value_name="Value")