# Clean dataset and save data to postgres database as well as to csv files

In [1]:
# !rm CHSICorrelations/data/CleanedCHSIDataset/CHSIsqlite.sqlite

In [2]:
import numpy as np
import pandas as pd

In [3]:
demographic_df = pd.read_csv("CHSICorrelations/data/CHSI_dataset/DEMOGRAPHICS.csv")

In [4]:
demographic_df.head()

,State_FIPS_Code,County_FIPS_Code,CHSI_County_Name,CHSI_State_Name,CHSI_State_Abbr,Strata_ID_Number,Strata_Determining_Factors,Number_Counties,Population_Size,Min_Population_Size,...,Max_Black,Native_American,Min_Native_American,Max_Native_American,Asian,Min_Asian,Max_Asian,Hispanic,Min_Hispanic,Max_Hispanic
0,1,1,Autauga,Alabama,AL,29,"frontier status, population size, poverty, age",37,48612,28447,...,17.3,0.5,0.1,1.1,0.6,0.2,2.2,1.7,0.8,19.2
1,1,3,Baldwin,Alabama,AL,16,"frontier status, population size, poverty, age",27,162586,118395,...,14.1,0.5,0.1,1.1,0.4,0.4,3.3,2.3,0.8,13.7
2,1,5,Barbour,Alabama,AL,51,"frontier status, population size, poverty, age...",33,28414,27269,...,50.7,0.4,0.2,7.1,0.3,0.2,2.3,3.1,1.0,67.7
3,1,7,Bibb,Alabama,AL,42,"frontier status, population size, poverty, age",53,21516,8134,...,35.4,0.3,0.1,2.6,0.1,0.1,1.5,1.4,1.2,46.9
4,1,9,Blount,Alabama,AL,28,"frontier status, population size, poverty, age",39,55725,29009,...,20.5,0.5,0.1,0.9,0.2,0.3,2.2,6.3,0.8,6.3

In [5]:
demographic_df.columns

Index(['State_FIPS_Code', 'County_FIPS_Code', 'CHSI_County_Name',
       'CHSI_State_Name', 'CHSI_State_Abbr', 'Strata_ID_Number',
       'Strata_Determining_Factors', 'Number_Counties', 'Population_Size',
       'Min_Population_Size', 'Max_Population_Size', 'Population_Density',
       'Min_Population_Density', 'Max_Population_Density', 'Poverty',
       'Min_Poverty', 'Max_Poverty', 'Age_19_Under', 'Min_Age_19_Under',
       'Max_Age_19_Under', 'Age_19_64', 'Min_Age_19_64', 'Max_Age_19_65',
       'Age_65_84', 'Min_Age_65_84', 'Max_Age_65_85', 'Age_85_and_Over',
       'Min_Age_85_and_Over', 'Max_Age_85_and_Over', 'White', 'Min_White',
       'Max_White', 'Black', 'Min_Black', 'Max_Black', 'Native_American',
       'Min_Native_American', 'Max_Native_American', 'Asian', 'Min_Asian',
       'Max_Asian', 'Hispanic', 'Min_Hispanic', 'Max_Hispanic'],
      dtype='object')

In [6]:
col = ["State_FIPS_Code", "CHSI_State_Name","County_FIPS_Code", "CHSI_County_Name", "CHSI_State_Abbr",
                         "Strata_ID_Number", "Strata_Determining_Factors", "Number_Counties", "Population_Size", "Poverty",
                         "Age_19_Under", "Age_19_64", "Age_65_84", "Age_85_and_Over", "White", "Black", "Native_American", "Asian", "Hispanic"]
demographic_df = demographic_df[col]
demographic_df.head()

,State_FIPS_Code,CHSI_State_Name,County_FIPS_Code,CHSI_County_Name,CHSI_State_Abbr,Strata_ID_Number,Strata_Determining_Factors,Number_Counties,Population_Size,Poverty,Age_19_Under,Age_19_64,Age_65_84,Age_85_and_Over,White,Black,Native_American,Asian,Hispanic
0,1,Alabama,1,Autauga,AL,29,"frontier status, population size, poverty, age",37,48612,10.4,26.9,62.3,9.8,0.9,80.7,17.3,0.5,0.6,1.7
1,1,Alabama,3,Baldwin,AL,16,"frontier status, population size, poverty, age",27,162586,10.2,23.5,60.3,14.5,1.8,88.4,9.9,0.5,0.4,2.3
2,1,Alabama,5,Barbour,AL,51,"frontier status, population size, poverty, age...",33,28414,22.1,24.3,62.5,11.6,1.6,52.2,46.8,0.4,0.3,3.1
3,1,Alabama,7,Bibb,AL,42,"frontier status, population size, poverty, age",53,21516,16.8,24.6,63.3,10.9,1.2,76.8,22.5,0.3,0.1,1.4
4,1,Alabama,9,Blount,AL,28,"frontier status, population size, poverty, age",39,55725,11.9,24.5,62.1,12.1,1.3,97.1,1.5,0.5,0.2,6.3

In [7]:
demographic_df.count()

State_FIPS_Code               3141
CHSI_State_Name               3141
County_FIPS_Code              3141
CHSI_County_Name              3141
CHSI_State_Abbr               3141
Strata_ID_Number              3141
Strata_Determining_Factors    3141
Number_Counties               3141
Population_Size               3141
Poverty                       3141
Age_19_Under                  3141
Age_19_64                     3141
Age_65_84                     3141
Age_85_and_Over               3141
White                         3141
Black                         3141
Native_American               3141
Asian                         3141
Hispanic                      3141
dtype: int64

In [8]:
subset = demographic_df.columns[9:]
demographic_df.dropna(subset=subset, how = 'all', inplace=True)

In [9]:
num = demographic_df._get_numeric_data()
num.head()
num[num < 0] = np.nan
demographic_df.head()

,State_FIPS_Code,CHSI_State_Name,County_FIPS_Code,CHSI_County_Name,CHSI_State_Abbr,Strata_ID_Number,Strata_Determining_Factors,Number_Counties,Population_Size,Poverty,Age_19_Under,Age_19_64,Age_65_84,Age_85_and_Over,White,Black,Native_American,Asian,Hispanic
0,1,Alabama,1,Autauga,AL,29,"frontier status, population size, poverty, age",37,48612,10.4,26.9,62.3,9.8,0.9,80.7,17.3,0.5,0.6,1.7
1,1,Alabama,3,Baldwin,AL,16,"frontier status, population size, poverty, age",27,162586,10.2,23.5,60.3,14.5,1.8,88.4,9.9,0.5,0.4,2.3
2,1,Alabama,5,Barbour,AL,51,"frontier status, population size, poverty, age...",33,28414,22.1,24.3,62.5,11.6,1.6,52.2,46.8,0.4,0.3,3.1
3,1,Alabama,7,Bibb,AL,42,"frontier status, population size, poverty, age",53,21516,16.8,24.6,63.3,10.9,1.2,76.8,22.5,0.3,0.1,1.4
4,1,Alabama,9,Blount,AL,28,"frontier status, population size, poverty, age",39,55725,11.9,24.5,62.1,12.1,1.3,97.1,1.5,0.5,0.2,6.3

In [10]:
demographic_df.dtypes

State_FIPS_Code                 int64
CHSI_State_Name                object
County_FIPS_Code                int64
CHSI_County_Name               object
CHSI_State_Abbr                object
Strata_ID_Number                int64
Strata_Determining_Factors     object
Number_Counties                 int64
Population_Size                 int64
Poverty                       float64
Age_19_Under                  float64
Age_19_64                     float64
Age_65_84                     float64
Age_85_and_Over               float64
White                         float64
Black                         float64
Native_American               float64
Asian                         float64
Hispanic                      float64
dtype: object

In [11]:
demographic_df.count()

State_FIPS_Code               3141
CHSI_State_Name               3141
County_FIPS_Code              3141
CHSI_County_Name              3141
CHSI_State_Abbr               3141
Strata_ID_Number              3141
Strata_Determining_Factors    3141
Number_Counties               3141
Population_Size               3141
Poverty                       3140
Age_19_Under                  3141
Age_19_64                     3141
Age_65_84                     3141
Age_85_and_Over               3141
White                         3141
Black                         3141
Native_American               3141
Asian                         3141
Hispanic                      3141
dtype: int64

In [12]:
s = demographic_df["Poverty"]
any(x < 0 for x in s)

False

In [13]:
demographic_df.columns = map(str.lower, demographic_df.columns)

In [14]:
demographic_df

,state_fips_code,chsi_state_name,county_fips_code,chsi_county_name,chsi_state_abbr,strata_id_number,strata_determining_factors,number_counties,population_size,poverty,age_19_under,age_19_64,age_65_84,age_85_and_over,white,black,native_american,asian,hispanic
0,1,Alabama,1,Autauga,AL,29,"frontier status, population size, poverty, age",37,48612,10.4,26.9,62.3,9.8,0.9,80.7,17.3,0.5,0.6,1.7
1,1,Alabama,3,Baldwin,AL,16,"frontier status, population size, poverty, age",27,162586,10.2,23.5,60.3,14.5,1.8,88.4,9.9,0.5,0.4,2.3
2,1,Alabama,5,Barbour,AL,51,"frontier status, population size, poverty, age...",33,28414,22.1,24.3,62.5,11.6,1.6,52.2,46.8,0.4,0.3,3.1
3,1,Alabama,7,Bibb,AL,42,"frontier status, population size, poverty, age",53,21516,16.8,24.6,63.3,10.9,1.2,76.8,22.5,0.3,0.1,1.4
4,1,Alabama,9,Blount,AL,28,"frontier status, population size, poverty, age",39,55725,11.9,24.5,62.1,12.1,1.3,97.1,1.5,0.5,0.2,6.3
5,1,Alabama,11,Bullock,AL,75,"frontier status, population size, poverty, age...",37,11055,26.2,24.7,63.2,10.0,2.2,27.8,71.4,0.4,0.2,5.9
6,1,Alabama,13,Butler,AL,76,"frontier status, population size, poverty, age...",38,20766,20.0,25.6,58.5,13.6,2.4,57.5,41.9,0.2,0.3,0.9
7,1,Alabama,15,Calhoun,AL,6,"frontier status, population size, poverty",53,112141,16.4,24.1,61.6,12.7,1.5,78.3,19.7,0.4,0.8,2.0
8,1,Alabama,17,Chambers,AL,50,"frontier status, population size, poverty, age...",27,35460,16.2,24.8,59.5,13.5,2.2,60.8,38.6,0.1,0.2,1.2
9,1,Alabama,19,Cherokee,AL,64,"frontier status, population size, poverty, age...",41,24522,15.2,21.9,61.4,15.2,1.4,93.3,5.5,0.3,0.3,1.1
10,1,Alabama,21,Chilton,AL,32,"frontier status, population size, poverty, age",37,41744,14.9,25.0,62.6,11.3,1.2,88.3,10.5,0.3,0.4,3.7
11,1,Alabama,23,Choctaw,AL,66,"frontier status, population size, poverty, age...",37,14807,18.7,24.9,59.5,13.7,2.0,55.7,43.9,0.1,0.1,0.8
12,1,Alabama,25,Clarke,AL,51,"frontier status, population size, poverty, age...",33,27269,19.2,27.3,58.5,12.4,1.8,55.8,43.7,0.2,0.2,0.7
13,1,Alabama,27,Clay,AL,63,"frontier status, population size, poverty, age...",32,13964,14.0,22.4,60.3,14.9,2.5,84.2,15.0,0.3,0.1,2.1
14,1,Alabama,29,Cleburne,AL,41,"frontier status, population size, poverty, age",47,14460,14.0,23.3,62.6,12.8,1.4,95.3,3.8,0.3,0.2,1.8
15,1,Alabama,31,Coffee,AL,32,"frontier status, population size, poverty, age",37,45567,13.7,24.5,61.1,12.9,1.5,77.9,18.5,0.9,1.2,3.2
16,1,Alabama,33,Colbert,AL,21,"frontier status, population size, poverty, age",44,54660,14.0,23.0,60.9,14.0,2.0,81.9,16.7,0.4,0.3,1.3
17,1,Alabama,35,Conecuh,AL,75,"frontier status, population size, poverty, age...",37,13257,22.0,25.3,59.3,13.4,2.1,55.3,44.1,0.2,0.1,0.9
18,1,Alabama,37,Coosa,AL,41,"frontier status, population size, poverty, age",47,11162,13.4,23.2,61.2,13.8,1.8,67.6,31.6,0.3,0.1,1.5
19,1,Alabama,39,Covington,AL,35,"frontier status, population size, poverty, age",27,37003,17.5,23.4,58.7,15.5,2.5,86.1,12.6,0.5,0.3,0.9
20,1,Alabama,41,Crenshaw,AL,71,"frontier status, population size, poverty, age...",33,13727,17.6,24.2,58.7,14.9,2.3,74.6,24.6,0.4,0.1,0.8
21,1,Alabama,43,Cullman,AL,21,"frontier status, population size, poverty, age",44,79886,13.3,23.9,61.3,13.3,1.5,97.3,1.2,0.4,0.3,3.1
22,1,Alabama,45,Dale,AL,33,"frontier status, population size, poverty, age",41,48748,15.8,27.7,59.4,11.8,1.2,75.5,20.9,0.5,1.3,3.2
23,1,Alabama,47,Dallas,AL,52,"frontier status, population size, poverty, age...",40,44366,25.0,29.0,57.4,12.1,1.5,32.4,66.9,0.1,0.3,0.6
24,1,Alabama,49,DeKalb,AL,24,"frontier status, population size, poverty, age",35,67271,15.1,25.0,61.2,12.3,1.6,96.0,1.8,0.8,0.3,8.8
25,1,Alabama,51,Elmore,AL,19,"frontier status, population size, poverty, age",37,73937,12.5,25.1,64.0,9.8,1.2,77.3,20.7,0.4,0.5,1.7
26,1,Alabama,53,Escambia,AL,51,"frontier status, population size, poverty, age...",33,38082,18.6,24.4,61.4,12.5,1.7,64.3,31.7,2.9,0.3,1.0
27,1,Alabama,55,Etowah,AL,6,"frontier status, population size, poverty",53,103189,15.7,24.0,60.3,13.9,1.8,83.8,14.6,0.3,0.5,2.4
28,1,Alabama,57,Fayette,AL,63,"frontier status, population size, poverty, age...",32,18228,16.1,23.5,60.4,13.6,2.4,87.4,11.8,0.2,0.3,0.9
29,1,Alabama,59,Franklin,AL,49,"frontier status, population size, poverty, age...",35,30737,17.4,24.6,60.2,13.7,1.5,94.1,4.2,0.4,0.6,10.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3111,55,Wisconsin,129,Washburn,WI,59,"frontier status, population size, poverty, age...",32,16601,9.7,21.6,59.3,16.3,2.8,97.5,0.3,1.0,0.2,1.0
3112,55,Wisconsin,131,Washington,WI,12,"frontier status, population size, poverty, age",57,126158,4.6,24.7,63.4,10.2,1.7,97.5,0.7,0.3,0.9,1.6
3113,55,Wisconsin,133,Waukesha,WI,10,"frontier status, population size, poverty, age",36,378971,4.1,24.6,62.5,11.2,1.7,95.6,1.1,0.2,2.2,3.0
3114,55,Wisconsin,135,Waupaca,WI,18,"frontier status, population size, poverty, age",20,52563,7.4,23.8,59.9,13.9,2.3,98.5,0.2,0.4,0.3,1.9
3115,55,Wisconsin,137,Waushara,WI,60,"frontier status, population size, poverty, age...",48,24789,9.6,21.6,60.1,15.9,2.5,98.0,0.7,0.4,0.4,4.6
3116,55,Wisconsin,139,Winnebago,WI,11,"frontier status, population size, poverty, age",44,159482,7.5,23.4,64.0,10.4,2.1,95.5,1.3,0.5,1.9,2.5
3117,55,Wisconsin,141,Wood,WI,45,"frontier status, population size, poverty, age...",38,75234,7.8,23.8,59.7,13.3,3.2,96.5,0.5,0.7,1.7,1.1
3118,56,Wyoming,1,Albany,WY,32,"frontier status, population size, poverty, age",37,30890,14.4,21.6,69.6,7.8,0.9,94.1,1.2,1.0,2.1,6.7
3119,56,Wyoming,3,Big Horn,WY,82,"frontier status, population size, poverty, age",37,11333,13.2,25.3,57.5,14.8,2.4,98.0,0.2,0.9,0.4,6.2
3120,56,Wyoming,5,Campbell,WY,47,"frontier status, population size, poverty, age...",34,37405,7.9,26.8,67.6,5.2,0.4,97.0,0.3,1.2,0.5,4.2
3121,56,Wyoming,7,Carbon,WY,80,"frontier status, population size, poverty, age",41,15331,12.2,21.4,65.2,11.8,1.5,96.3,1.0,1.2,1.0,13.0
3122,56,Wyoming,9,Converse,WY,80,"frontier status, population size, poverty, age",41,12766,10.5,23.9,63.9,11.1,1.1,97.8,0.1,0.9,0.3,4.5
3123,56,Wyoming,11,Crook,WY,78,"frontier status, population size, poverty, age",43,6182,8.5,21.9,62.0,13.8,2.3,98.5,0.1,1.1,0.1,1.1
3124,56,Wyoming,13,Fremont,WY,77,"frontier status, population size",15,36491,12.9,25.4,60.4,12.8,1.4,77.5,0.3,20.6,0.3,4.8
3125,56,Wyoming,15,Goshen,WY,84,"frontier status, population size, poverty, age",52,12243,14.6,22.7,58.9,15.1,3.3,98.1,0.2,1.0,0.3,9.0
3126,56,Wyoming,17,Hot Springs,WY,81,"frontier status, population size, poverty, age",58,4537,11.6,18.3,59.7,18.7,3.3,97.0,0.6,1.6,0.4,2.5
3127,56,Wyoming,19,Johnson,WY,81,"frontier status, population size, poverty, age",58,7721,9.6,20.6,62.0,15.1,2.4,98.2,0.1,0.7,0.2,2.2
3128,56,Wyoming,21,Laramie,WY,17,"frontier status, population size, poverty, age",32,85163,9.9,25.0,63.0,10.4,1.6,93.1,2.6,0.9,1.2,10.6
3129,56,Wyoming,23,Lincoln,WY,78,"frontier status, population size, poverty, age",43,15999,9.5,26.1,61.3,11.2,1.3,98.1,0.1,0.6,0.3,2.6
3130,56,Wyoming,25,Natrona,WY,20,"frontier status, population size, poverty, age",32,69799,12.1,24.7,62.6,11.3,1.4,96.2,1.0,1.1,0.4,4.9
3131,56,Wyoming,27,Niobrara,WY,84,"frontier status, population size, poverty, age",52,2286,14.1,19.6,61.4,15.6,3.4,99.0,0.2,0.5,0.1,1.6
3132,56,Wyoming,29,Park,WY,77,"frontier status, population size",15,26664,11.7,21.8,62.4,13.5,2.3,98.1,0.1,0.5,0.4,4.0
3133,56,Wyoming,31,Platte,WY,81,"frontier status, population size, poverty, age",58,8619,11.5,21.4,61.2,15.3,2.2,98.5,0.2,0.6,0.2,5.5
3134,56,Wyoming,33,Sheridan,WY,30,"frontier status, population size, poverty, age",57,27389,11.5,22.2,62.4,13.3,2.1,96.9,0.3,1.5,0.4,2.6
3135,56,Wyoming,35,Sublette,WY,78,"frontier status, population size, poverty, age",43,6926,7.7,22.4,66.6,9.9,1.0,98.4,0.3,0.6,0.3,2.7
3136,56,Wyoming,37,Sweetwater,WY,77,"frontier status, population size",15,37975,8.6,26.6,65.1,7.4,0.9,95.5,1.1,1.1,1.0,10.3
3137,56,Wyoming,39,Teton,WY,78,"frontier status, population size, poverty, age",43,19032,5.6,18.8,73.3,7.5,0.4,97.9,0.2,0.4,0.8,10.2
3138,56,Wyoming,41,Uinta,WY,38,"frontier status, population size, poverty, age",35,19939,10.6,29.1,63.1,7.0,0.8,97.5,0.1,1.1,0.3,5.9
3139,56,Wyoming,43,Washakie,WY,82,"frontier status, population size, poverty, age",37,7933,11.1,23.5,59.5,14.6,2.3,97.2,0.2,0.8,0.7,12.1
3140,56,Wyoming,45,Weston,WY,78,"frontier status, population size, poverty, age",43,6671,9.9,20.1,63.2,14.4,2.4,97.6,0.1,1.4,0.2,2.3

In [15]:
demographic_df.to_csv("CHSICorrelations/data/CleanedCHSIDataset/DemographicData.csv", index=False)

In [16]:
from sqlalchemy import create_engine

In [17]:
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, Float, ForeignKey, ForeignKeyConstraint

In [18]:
# demographic_df["County_FIPS_Code"].value_counts()
dup = demographic_df[demographic_df["county_fips_code"] == 55]
dup.head()

,state_fips_code,chsi_state_name,county_fips_code,chsi_county_name,chsi_state_abbr,strata_id_number,strata_determining_factors,number_counties,population_size,poverty,age_19_under,age_19_64,age_65_84,age_85_and_over,white,black,native_american,asian,hispanic
27,1,Alabama,55,Etowah,AL,6,"frontier status, population size, poverty",53,103189,15.7,24.0,60.3,13.9,1.8,83.8,14.6,0.3,0.5,2.4
136,5,Arkansas,55,Greene,AR,50,"frontier status, population size, poverty, age...",27,39401,15.4,25.3,60.9,12.2,1.6,97.8,0.3,0.4,0.2,1.5
211,6,California,55,Napa,CA,13,"frontier status, population size, poverty, age",16,132764,7.9,24.7,60.8,12.1,2.4,89.3,2.0,1.0,5.6,27.3
270,8,Colorado,55,Huerfano,CO,87,"frontier status, population size, poverty, age",32,7771,19.2,20.4,61.0,15.9,2.8,91.9,3.0,3.3,0.6,34.3
344,12,Florida,55,Highlands,FL,24,"frontier status, population size, poverty, age",35,95496,13.9,20.0,48.9,26.7,4.3,88.0,9.6,0.5,1.3,15.0

In [19]:
riskfactor_df = pd.read_csv("CHSICorrelations/data/CHSI_dataset/RISKFACTORSANDACCESSTOCARE.csv")

riskfactor_df.head()

# riskfactor_df.loc[~(riskfactor_df["No_Exercise"] > 0), "No_Exercise"]=np.nan


num = riskfactor_df._get_numeric_data()
num.head()
num[num < 0] = np.nan
riskfactor_df.head()

riskfactor_df.count()

col = ["State_FIPS_Code", "County_FIPS_Code", "No_Exercise", "Few_Fruit_Veg", 
       "Obesity","High_Blood_Pres", "Smoker", "Diabetes", "Uninsured", "Prim_Care_Phys_Rate", "Dentist_Rate", "Community_Health_Center_Ind"]
    
riskfactor_df = riskfactor_df[col]
riskfactor_df.head()

riskfactor_df.rename(columns={"State_FIPS_Code": "State_Code", "County_FIPS_Code":"County_Code"}, inplace=True)
# riskfactor_df.rename(columns={"State_FIPS_Code": "state_code", "County_FIPS_Code":"county_code",
#                              "No_Exercise":"no_exercise", "Few_Fruit_Veg":"few_fruit_veg", "Obesity": "obesity",
#                              }, inplace=True)

riskfactor_df.columns = map(str.lower, riskfactor_df.columns)

riskfactor_df.head()

riskfactor_df.to_csv("CHSICorrelations/data/CleanedCHSIDataset/Riskfactors_AccessToCare.csv", index=False)

In [20]:
riskfactor_df.head()

,state_code,county_code,no_exercise,few_fruit_veg,obesity,high_blood_pres,smoker,diabetes,uninsured,prim_care_phys_rate,dentist_rate,community_health_center_ind
0,1,1,27.8,78.6,24.5,29.1,26.6,14.2,5690,45.3,22.6,1
1,1,3,27.2,76.2,23.6,30.5,24.6,7.2,19798,67.0,30.8,1
2,1,5,NaN,NaN,25.6,NaN,17.7,6.6,5126,45.8,24.6,1
3,1,7,NaN,86.6,NaN,NaN,NaN,13.1,3315,41.8,18.6,1
4,1,9,33.5,74.6,24.2,NaN,23.6,8.4,8131,16.2,10.8,2

In [21]:
prvntv_srvc_use_df = pd.read_csv("CHSICorrelations/data/CHSI_dataset/PREVENTIVESERVICESUSE.csv")

prvntv_srvc_use_df.head()

,State_FIPS_Code,County_FIPS_Code,CHSI_County_Name,CHSI_State_Name,CHSI_State_Abbr,Strata_ID_Number,FluB_Rpt,FluB_Ind,FluB_Exp,HepA_Rpt,...,CI_Max_Mammogram,Proctoscopy,CI_Min_Proctoscopy,CI_Max_Proctoscopy,Pneumo_Vax,CI_Min_Pneumo_Vax,CI_Max_Pneumo_Vax,Flu_Vac,CI_Min_Flu_Vac,CI_Max_Flu_Vac
0,1,1,Autauga,Alabama,AL,29,0,3,0,1,...,-1111.1,-1111.1,-1111.1,-1111.1,-1111.1,-1111.1,-1111.1,-1111.1,-1111.1,-1111.1
1,1,3,Baldwin,Alabama,AL,16,0,3,4,2,...,89.6,44.1,37.2,51.1,58.7,50.8,66.6,61.8,54.1,69.4
2,1,5,Barbour,Alabama,AL,51,0,3,0,2,...,-1111.1,-1111.1,-1111.1,-1111.1,-1111.1,-1111.1,-1111.1,-1111.1,-1111.1,-1111.1
3,1,7,Bibb,Alabama,AL,42,0,3,0,2,...,-1111.1,-1111.1,-1111.1,-1111.1,-1111.1,-1111.1,-1111.1,-1111.1,-1111.1,-1111.1
4,1,9,Blount,Alabama,AL,28,2,4,3,3,...,-1111.1,-1111.1,-1111.1,-1111.1,-1111.1,-1111.1,-1111.1,-1111.1,-1111.1,-1111.1

In [22]:
prvntv_srvc_use_df.columns

Index(['State_FIPS_Code', 'County_FIPS_Code', 'CHSI_County_Name',
       'CHSI_State_Name', 'CHSI_State_Abbr', 'Strata_ID_Number', 'FluB_Rpt',
       'FluB_Ind', 'FluB_Exp', 'HepA_Rpt', 'HepA_Ind', 'HepA_Exp', 'HepB_Rpt',
       'HepB_Ind', 'HepB_Exp', 'Meas_Rpt', 'Meas_Ind', 'Meas_Exp', 'Pert_Rpt',
       'Pert_Ind', 'Pert_Exp', 'CRS_Rpt', 'CRS_Ind', 'CRS_Exp', 'Syphilis_Rpt',
       'Syphilis_Ind', 'Syphilis_Exp', 'ID_Time_Span', 'Pap_Smear',
       'CI_Min_Pap_Smear', 'CI_Max_Pap_Smear', 'Mammogram', 'CI_Min_Mammogram',
       'CI_Max_Mammogram', 'Proctoscopy', 'CI_Min_Proctoscopy',
       'CI_Max_Proctoscopy', 'Pneumo_Vax', 'CI_Min_Pneumo_Vax',
       'CI_Max_Pneumo_Vax', 'Flu_Vac', 'CI_Min_Flu_Vac', 'CI_Max_Flu_Vac'],
      dtype='object')

In [23]:
num = prvntv_srvc_use_df._get_numeric_data()
num.head()
num[num < 0] = np.nan
prvntv_srvc_use_df.head()

prvntv_srvc_use_df.count()

col = ["State_FIPS_Code", "County_FIPS_Code", "Pap_Smear", "Mammogram", 
       "Proctoscopy", "Pneumo_Vax", "Flu_Vac"]
    
prvntv_srvc_use_df = prvntv_srvc_use_df[col]
prvntv_srvc_use_df.head()

prvntv_srvc_use_df.rename(columns={"State_FIPS_Code": "State_Code", "County_FIPS_Code":"County_Code"}, inplace=True)

prvntv_srvc_use_df.columns = map(str.lower, prvntv_srvc_use_df.columns)

prvntv_srvc_use_df.head()

,state_code,county_code,pap_smear,mammogram,proctoscopy,pneumo_vax,flu_vac
0,1,1,NaN,NaN,NaN,NaN,NaN
1,1,3,86.1,82.0,44.1,58.7,61.8
2,1,5,NaN,NaN,NaN,NaN,NaN
3,1,7,NaN,NaN,NaN,NaN,NaN
4,1,9,87.2,NaN,NaN,NaN,NaN

In [24]:
# df = df[df.iloc[:, [2,3]].notnull().all(axis=1)]
# prvntv_srvc_use_df = prvntv_srvc_use_df[prvntv_srvc_use_df.iloc[:, [2,3,4,5,6]].all(axis=1)]

In [25]:
prvntv_srvc_use_df.head()

,state_code,county_code,pap_smear,mammogram,proctoscopy,pneumo_vax,flu_vac
0,1,1,NaN,NaN,NaN,NaN,NaN
1,1,3,86.1,82.0,44.1,58.7,61.8
2,1,5,NaN,NaN,NaN,NaN,NaN
3,1,7,NaN,NaN,NaN,NaN,NaN
4,1,9,87.2,NaN,NaN,NaN,NaN

In [26]:
# subset = ["pap_smear", "mammogram", "proctoscopy", "pneumo_vax", "flu_vac"]
subset = prvntv_srvc_use_df.columns[2:]
prvntv_srvc_use_df.dropna(subset=subset, how = 'all', inplace=True)

In [27]:
prvntv_srvc_use_df.to_csv("CHSICorrelations/data/CleanedCHSIDataset/PreventiveServiceUse.csv", index=False)

In [28]:
!pip install psycopg2
!pip install psycopg2-binary

# https://docs.sqlalchemy.org/en/13/dialects/postgresql.html#module-sqlalchemy.dialects.postgresql.psycopg2
# postgresql+psycopg2://user:password@host:port/dbname[?key=value&key=value...]

# # use for postgres
# user = "postgres"
# password = "changeme"
# host = "localhost"
# port = "5432" # 5432 for everyone else
# db = "CHSI_db"
# uri = f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{db}"
# uri

SyntaxError: invalid syntax (<ipython-input-28-3c14a21611b4>, line 4)

In [ ]:
# uri = "sqlite:///CHSICorrelations/data/CleanedCHSIDataset/CHSIsqlite.sqlite"
uri = "postgres://wsbowxbgvnsmii:4d965ff9780107fd692861d081475b30afe4760f22851cdd837f66aa9702a69e@ec2-23-21-249-0.compute-1.amazonaws.com:5432/d7k1n87jldddg5"

In [ ]:
Base = declarative_base()
class Demographic_data(Base):
    __tablename__ = "demographic_data"
    state_fips_code = Column(Integer, primary_key=True)     
    chsi_state_name = Column(String(255))
    county_fips_code = Column(Integer, primary_key=True)
    chsi_county_name = Column(String(255))
    chsi_state_abbr = Column(String(255))
    strata_id_number =  Column(Integer)     
    strata_determining_factors = Column(String(255))
    number_counties =  Column(Integer)     
    population_size =  Column(Integer)     
    poverty = Column(Float)
    age_19_under = Column(Float)
    age_19_64 = Column(Float)
    age_65_84 = Column(Float)
    age_85_and_over = Column(Float)
    white = Column(Float)
    black = Column(Float)
    native_american = Column(Float)
    asian = Column(Float)
    hispanic = Column(Float)

class Riskfactor_data(Base):
    __tablename__ = "riskfactor_data"
    riskfactor_id = Column(Integer, primary_key=True)
    state_code = Column(Integer)     
    county_code = Column(Integer)
    no_exercise = Column(Float)
    few_fruit_veg = Column(Float)
    obesity = Column(Float)
    high_blood_pres = Column(Float)
    smoker = Column(Float)
    diabetes = Column(Float)
    uninsured = Column(Float)
    prim_care_phys_rate = Column(Float)
    dentist_rate = Column(Float)
    community_health_center_ind = Column(Float)
    __table_args__ = (ForeignKeyConstraint([county_code, state_code],
                                           [Demographic_data.county_fips_code, Demographic_data.state_fips_code]),
                      {})

In [ ]:
# Create the connection engine
engine = create_engine(uri)
conn = engine.connect()

# Base.metadata.drop_all(conn)
Base.metadata.create_all(conn)

In [ ]:
demographic_df.to_sql(Demographic_data.__tablename__, conn, index=False, if_exists="append")

In [ ]:
riskfactor_df.to_sql(Riskfactor_data.__tablename__, conn, index=False, if_exists="append")